name: First action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up R 4.2
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'
      - name: Install renv
        run: Rscript -e 'install.packages("renv", type = "source")'
      - name: Install packages
        run: Rscript -e 'renv::restore()'
      - name: Format files
        run: Rscript -e 'styler::style_dir(path = c("R", "tests"))'



