name: First action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up R 4.2
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'
      - name: Install dependencies
        run: |
          make install
      - name: A test
        shell: bash
        run: |
          echo "options(renv.config.pak.enabled = TRUE, repos = c(RSPM = 'https://packagemanager.rstudio.com/all/__linux__/focal}/latest', CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" >> /usr/local/lib/R/etc/Rprofile.site
      - name: Install and activate renv
        shell: Rscript {0}
        run: |
          install.packages("renv")
      - name: Restore packages
        shell: Rscript {0}
        run: |
          renv::restore()