name: First action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up R 4.2
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'
      - name: Install dependencies
        run: |
          make install
      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
      - name: Lint
        run: |
          make lint