name: First action

jobs:
  build:
    runs-on: debian-stable
    steps:
    - uses: actions/checkout@v2
    - name: Setup R
    - uses: r-lib/actions/setup-r@master
        with:
            r-version: '4.2'



