name: First action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up R 4.2
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'
      - name: Install pak
        run: Rscript -e 'install.packages("pak", type = "source")'
      - name: Install renv, styler and lintr
        run: Rscript -e "pak::pkg_install('renv', 'styler', 'lintr')"
      - name: Restore environment
        run: Rscript -e 'renv::restore()'
      - name: Format
        run: Rscript -e 'styler::style_dir(path = c("R", "tests"))'
      - name: Lint
        run: RScript -e 'purrr::walk(c("R", "test"), lintr::lint_dir)'



